{% set name = "gstlal-calibration" %}
{% set version = "1.3.1" %}

# dependencies
{% set gstlal_version = "1.8.0" %}
{% set gstlal_ugly_version = "1.9.0" %}
{% set lal_version = "7.1.0" %}
{% set lalmetaio_version = "2.0.0" %}
{% set ligo_segments_version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 0d1bc7d17879873ed66c76446ba11b7d26a0c281f4740dd763b0a581102afa9b
  patches:
    - missing-links.patch

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - fftw
    - gsl
    - gstreamer
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - libglib
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - python
  run:
    - fftw
    - gsl
    - gstreamer
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - kafka-python
    - libglib
    - liblal >={{ lal_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - ligo-scald
    - ligo-segments >={{ ligo_segments_version }}
    - numpy
    - python
    - python-lal
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  imports:
    - gstlal.calibhandler
    - gstlal.calibration_parts
  commands:
    # check executables
    - gstlal_calibration_aggregator --help
    - gstlal_compute_strain --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (calibration parts)
  description: |
    This package contains the plugins and shared libraries required to
    run the gstlal calibration software.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
