{% set name = "gstlal-calibration" %}
{% set version = "1.5.7" %}

# dependencies
{% set gstlal_version = "1.10.0" %}
{% set gstlal_ugly_version = "1.10.0" %}
{% set lal_version = "7.2.4" %}
{% set lalmetaio_version = "3.0.2" %}
{% set ligo_segments_version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 374c4e9b5284e8e1d49d7bbc78ec5243714d17c500ac8881cee7088e4b2a9e5d
  patches:
    # patch use of imp module in py-compile (old autoconf)
    - py-compile-imp.patch
    # patch fix for https://git.ligo.org/Calibration/gstlal-calibration/-/issues/18
    - link-fftw.patch
    # patch fix for https://git.ligo.org/Calibration/gstlal-calibration/-/issues/26
    - link-gsl.patch

build:
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - fftw
    - gsl
    - gst-plugins-base
    - gstreamer
    - gstlal >={{ gstlal_version }}
    - libglib
    - liblal >={{ lal_version }}
    #- numpy  <-- not linked against, allow gstlal to bring it in for us
    - python
  run:
    - fftw
    - gsl
    - gst-plugins-base
    - gstreamer
    - gstlal >={{ gstlal_version }}
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - kafka-python-ng
    - libglib
    - liblal >={{ lal_version }}
    - ligo-scald
    - ligo-segments >={{ ligo_segments_version }}
    - matplotlib-base
    - numpy
    - python
    - python-lal
    - scipy

test:
  imports:
    - gstlalcalibration.calibhandler
    - gstlalcalibration.calibration_parts
  commands:
    # check plugins
    - gst-inspect-1.0 cmath
    - gst-inspect-1.0 gstlalcalibration
    - gst-inspect-1.0 splitcounter
    # check executables
    - gstlal_calibration_aggregator --help
    - gstlal_compute_strain --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (calibration parts)
  description: |
    This package contains the plugins and shared libraries required to
    run the gstlal calibration software.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
